package com.projectswg.tools.csc.conversationeditor;

import com.projectswg.tools.csc.conversationeditor.actions.SaveConversation;
import java.awt.Point;
import java.io.IOException;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.ExplorerUtils;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;
import org.xml.sax.SAXException;

@ConvertAsProperties(
        dtd = "-//com.projectswg.tools.csc.conversationeditor//Editor//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "EditorTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE", 
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "editor", openAtStartup = true)
@ActionID(category = "Window", id = "com.projectswg.tools.csc.conversationeditor.EditorTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "Editor",
        preferredID = "EditorTopComponent"
)
@Messages({
    "CTL_EditorAction=Conversation Editor",
    "CTL_EditorTopComponent=Conversation Editor",
    "HINT_EditorTopComponent=Conversation Editor window"
})
public final class EditorTopComponent extends TopComponent implements ExplorerManager.Provider {

    private final ExplorerManager mgr = new ExplorerManager();
    private final SceneView scene;
    
    // New Conversation
    public EditorTopComponent() {
        initComponents();

        setToolTipText(Bundle.HINT_EditorTopComponent());

        SceneView scene = new SceneView(mgr);
        scrollPane.setViewportView(scene.createView());

        setName(Bundle.CTL_EditorTopComponent() + " - *New Conversation*");
        
        scene.addNode(new ConversationNode("Begin Conversation", false, 0, false, true, 0));
        scene.addNode(new ConversationNode("End Conversation", false, 1, true, false, 0));

        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));   
        this.scene = scene;
    }
    
    // Open Conversation
    public EditorTopComponent(String convName) {
         initComponents();

        setToolTipText(Bundle.HINT_EditorTopComponent());

        SceneView scene = new SceneView(mgr);
        scene.setSceneName(convName);
        
        scrollPane.setViewportView(scene.createView());

        setName(Bundle.CTL_EditorTopComponent() + " - " + (scene.getSceneName().equals("") ? "*New Conversation*" : scene.getSceneName()));
        
        associateLookup(ExplorerUtils.createLookup(mgr, getActionMap()));   
        this.scene = scene;       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        /*try {
            SaveConversation.save(scene);
        } catch (ParserConfigurationException | IOException | SAXException | TransformerException ex) {
            Exceptions.printStackTrace(ex);
        }*/
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    public ExplorerManager getExplorerManager() {
        return mgr;
    }

    public SceneView getScene() {
        return scene;
    }
}
